networks:
  internal:
  external:

services:
  database:
    image: docker.io/library/postgres:17-bookworm
    container_name: mietmiez-postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      # if changing this, change in backend-config.yml as well!
      - POSTGRES_PASSWORD=supersecretlongandcomplexpassword
      - POSTGRES_USER=mietmiez
      - POSTGRES_DB=mietmiez

  backend:
    container_name: mietmiez-backend
    restart: always
    tty: true
    healthcheck:
      test: ["CMD", "wget --spider --no-verbose --tries=1 http://localhost:8080/v1/health"]
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal
    build:
      context: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend-config.yml:/app/config.yml
    